apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart-back.fullname" . }}
  labels:
    {{- include "helm-chart-back.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "helm-chart-back.selectorLabels" . | nindent 4 }}
