apiVersion: v1
kind: Service
metadata:
  name: {{ include "Backend.fullname" . }}
  labels:
    {{- include "Backend.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort | default "null" }}
  selector:
    app: {{ include "Backend.name" . }}
