
name: Push Docker Image to Docker Hub

on:
    push:
        branches: ['main']
        tags:
        - '**'
  
jobs:
    release:
        runs-on: ubuntu-latest
  
        steps:
        - uses: actions/checkout@v3
  
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PW }}
  
        - name: Build and Push Docker images
          run: |
            # docker build -t ${{ secrets.DOCKER_USERNAME }}/midterm:dtb_image /dtb && docker push ${{ secrets.DOCKER_USERNAME }}/midterm:dtb_image
            docker build -t ${{ secrets.DOCKER_USERNAME }}/midterm:back_image /back && docker push ${{ secrets.DOCKER_USERNAME }}/midterm:back_image
            # docker build -t ${{ secrets.DOCKER_USERNAME }}/midterm:front_image /vdt-front && docker push ${{ secrets.DOCKER_USERNAME }}/midterm:front_image

